name: 'eia_commodity_analytics'
version: '1.0.0'
config-version: 2

profile: 'athena' # Harus match dengan profiles.yml

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  eia_commodity_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics

